from Vehicle import Vehicle
from Ship import Ship
from Airplane import Airplane
from Person import Person
from Job import Job
from Driver import Driver

# Isi atribut Vehicle
v1 = Vehicle()
v1.setType("Airbus A380")
v1.setAge(17)
v1.setMaxPassengers(850)
v1.setFuelType("Jet A-1")
v1.setSpeed(1185)

v2 = Vehicle()
v2.setType("Airbus A340-600")
v2.setAge(31)
v2.setMaxPassengers(370)
v2.setFuelType("Jet A")
v2.setSpeed(914)

v3 = Vehicle()
v3.setType("Concorde")
v3.setAge(57)
v3.setMaxPassengers(100)
v3.setFuelType("Jet A-1")
v3.setSpeed(2179)

v4 = Vehicle()
v4.setType("Cruise Ship")
v4.setAge(12)
v4.setMaxPassengers(6780)
v4.setFuelType("Diesel")
v4.setSpeed(42)

v5 = Vehicle()
v5.setType("Ferry")
v5.setAge(15)
v5.setMaxPassengers(2812)
v5.setFuelType("Diesel")
v5.setSpeed(41)

print("+--------------------------------------+")
print("| Vehicle Class                        |")
print("+--------------------------------------+")
v1.printVehicle()
v2.printVehicle()
v3.printVehicle()
v4.printVehicle()
v5.printVehicle()

# Isi atribut Ship
s1 = Ship()
s1.setName("Wonder of the Seas")
s1.setType("Cruise Ship")
s1.setAge(0)
s1.setMaxPassengers(6988)
s1.setFuelType("Diesel")
s1.setCountryOfManufacture("France")

s2 = Ship()
s2.setName("Allure of the Seas")
s2.setType("Cruise Ship")
s2.setAge(12)
s2.setMaxPassengers(6780)
s2.setFuelType("Diesel")
s2.setCountryOfManufacture("Finland")

s3 = Ship()
s3.setName("MS Color Magic")
s3.setType("Ferry")
s3.setAge(15)
s3.setMaxPassengers(2812)
s3.setFuelType("Diesel")
s3.setCountryOfManufacture("Finland")

s4 = Ship()
s4.setName("MS Viking Glory")
s4.setType("Ferry")
s4.setAge(1)
s4.setMaxPassengers(2800)
s4.setFuelType("Liquefied Natural Gas")
s4.setCountryOfManufacture("China")

s5 = Ship()
s5.setName("MS Iona")
s5.setType("Cruise Ship")
s5.setAge(2)
s5.setMaxPassengers(6600)
s5.setFuelType("Liquefied Natural Gas")
s5.setCountryOfManufacture("Germany")

print("+--------------------------------------+")
print("| Ship Class                           |")
print("+--------------------------------------+")
s1.printShip()
s2.printShip()
s3.printShip()
s4.printShip()
s5.printShip()

# Isi atribut Airplane
a1 = Airplane()
a1.setType("Airbus A380")
a1.setAge(17)
a1.setMaxPassengers(850)
a1.setFuelType("Jet A-1")
a1.setWingsLength(79.8)
a1.setLongestDistance(16105)

a2 = Airplane()
a2.setType("Airbus A340-600")
a2.setAge(31)
a2.setMaxPassengers(370)
a2.setFuelType("Jet A")
a2.setWingsLength(63.45)
a2.setLongestDistance(16670)

a3 = Airplane()
a3.setType("Concorde")
a3.setAge(57)
a3.setMaxPassengers(100)
a3.setFuelType("Jet A-1")
a3.setWingsLength(25.6)
a3.setLongestDistance(7242)

a4 = Airplane()
a4.setType("Boeing 777")
a4.setAge(29)
a4.setMaxPassengers(368)
a4.setFuelType("Jet A")
a4.setWingsLength(64.8)
a4.setLongestDistance(16170)

a5 = Airplane()
a5.setType("Boeing 767")
a5.setAge(41)
a5.setMaxPassengers(275)
a5.setFuelType("Jet A-1")
a5.setWingsLength(47.6)
a5.setLongestDistance(7130)

print("+--------------------------------------+")
print("| Airplane Class                       |")
print("+--------------------------------------+")
a1.printAirplane()
a2.printAirplane()
a3.printAirplane()
a4.printAirplane()
a5.printAirplane()

# Isi atribut Person
p1 = Person()
p1.setNIK(3123456789)
p1.setName("Sarah")
p1.setGender("F")

p2 = Person()
p2.setNIK(3102913802)
p2.setName("Raven")
p2.setGender("F")

p3 = Person()
p3.setNIK(3198765432)
p3.setName("Abi")
p3.setGender("M")

p4 = Person()
p4.setNIK(3113138022)
p4.setName("Mario")
p4.setGender("M")

p5 = Person()
p5.setNIK(3202413802)
p5.setName("Eidy")
p5.setGender("M")

print("+--------------------------------------+")
print("| Person Class                         |")
print("+--------------------------------------+")
p1.printPerson()
p2.printPerson()
p3.printPerson()
p4.printPerson()
p5.printPerson()

# Isi atribut Job
j1 = Job()
j1.setNIP(21201012)
j1.setCompanyName("Drivin")
j1.setPosition("CEO")

j2 = Job()
j2.setNIP(9120919)
j2.setCompanyName("Drivin")
j2.setPosition("Secretary")

j3 = Job()
j3.setNIP(78965431)
j3.setCompanyName("Drivin")
j3.setPosition("Employee")

j4 = Job()
j4.setNIP(4563217)
j4.setCompanyName("Cariot")
j4.setPosition("CEO")

j5 = Job()
j5.setNIP(32147865)
j5.setCompanyName("Cariot")
j5.setPosition("CEO")

print("+--------------------------------------+")
print("| Job Class                            |")
print("+--------------------------------------+")
j1.printJob()
j2.printJob()
j3.printJob()
j4.printJob()
j5.printJob()

# Isi atribut Driver
d1 = Driver()
d1.setNIK(3123456789)
d1.setName("Sarah")
d1.setGender("F")
d1.setNIP(21201012)
d1.setCompanyName("Drivin")
d1.setPosition("CEO")
d1.setLicenseID("A101")
d1.setActiveUntil("01/12/23")
d1.setVehicleType("Motorcycles")

d2 = Driver()
d2.setNIK(3102913802)
d2.setName("Raven")
d2.setGender("F")
d2.setNIP(9120919)
d2.setCompanyName("Drivin")
d2.setPosition("Secretary")
d2.setLicenseID("B202")
d2.setActiveUntil("18/02/26")
d2.setVehicleType("Cars")

d3 = Driver()
d3.setNIK(3198765432)
d3.setName("Abi")
d3.setGender("M")
d3.setNIP(78965431)
d3.setCompanyName("Drivin")
d3.setPosition("Employee")
d3.setLicenseID("C1E01")
d3.setActiveUntil("17/07/27")
d3.setVehicleType("Medium-sized Vehicles")

d4 = Driver()
d4.setNIK(3113138022)
d4.setName("Mario")
d4.setGender("M")
d4.setNIP(4563217)
d4.setCompanyName("Cariot")
d4.setPosition("CEO")
d4.setLicenseID("C202")
d4.setActiveUntil("31/12/23")
d4.setVehicleType("Large Vehicles")

d5 = Driver()
d5.setNIK(3202413802)
d5.setName("Eidy")
d5.setGender("M")
d5.setNIP(32147865)
d5.setCompanyName("Cariot")
d5.setPosition("CEO")
d5.setLicenseID("D823")
d5.setActiveUntil("18/02/24")
d5.setVehicleType("Buses")

print("+--------------------------------------+")
print("| Driver Class                         |")
print("+--------------------------------------+")
d1.printDriver()
d2.printDriver()
d3.printDriver()
d4.printDriver()
d5.printDriver()